### ISSUE TITLE
Upgrade to rubocop 0.29.1; bump gem

### ISSUE THREAD

**Issue by saizai** [tj/commander#103]
@ggilder commander's rubocop version is out of date, and the rspec hasn't been bumped in the gem yet, which causes dependency issues.

**Comment by ggilder** [comment]
@saizai both of those dependencies are actually fixed on https://github.com/commander-rb/commander - I'm in the process of moving the project there, just haven't finished moving issues and updating links everywhere.

However, since both rubocop and rspec are only development dependencies, they should not be installed during a regular `gem install` or `bundle install`, so commander should not be able to cause dependency conflicts on those.

I'll update the gem later today once I've finished moving the repo; please open another issue if you continue to see dependency conflicts.

**Comment by saizai** [comment]
@ggilder Didn't realize you were moving it over. Sounds good. :)
