### ISSUE TITLE
Support for pry

### ISSUE THREAD

**Issue by KrauseFx** [tj/commander#83]
When using `commander` with [pry](https://github.com/pry/pry) I get the following error when using `binding.pry`:

```
before_session hook failed: NoMethodError: undefined method `process_line' for #<Hash:0x007f8aa253cdf0>
.../.rvm/gems/ruby-2.0.0-p481@global/gems/pry-0.10.1/lib/pry/pry_instance.rb:448:in `run_command'
```

I don't know if it's a `commander` or a `pry` issue. 

I still get to enter some code, but the results are not displayed.

**Comment by toobulkeh** [comment]
Running into this requirement with a thoroughly established gemset -- github.com/nomad/cupertino. Unfortunately, I don't want to change to this `require 'commander'` set, so it seems like I'm stuck without pry.

What do you use for writing/creating Gems and you want a simple debugger to start playing around with data structures while developing code? Since I can't use `binding.pry` I need another solution :(

**Comment by ggilder** [comment]
@toobulkeh wish I had a good answer for you; I always use pry too. Unfortunately it seems this is not uncommon; see for instance https://github.com/davetron5000/gli/issues/196

I've filed an issue for pry here: https://github.com/pry/pry/issues/1344

You could try the debugger gem: https://github.com/cldwalker/debugger — definitely less features but it might do in a pinch for light debugging needs.

Global namespaces are a pain :(

**Comment by ralfclaassens** [comment]
@toobulkeh I always use **byebug** instead: https://github.com/deivid-rodriguez/byebug. Does that help you?

**Comment by toobulkeh** [comment]
Yeah, I used byebug last night to just move forward. Definitely debugger :+1: for ruby 2.x.

I'm pretty new to non-rails dev, so my workflow is lacking, so thanks for the help!
